JW-991 cleanup
codilime/contrail-sandesh pull request #21
Opened 2017-08-10 14:30 UTC by michal-clapinski

2017-08-10 14:41 UTC, m-kostrzewa approved these changes

2017-08-10 14:44 UTC, katrybacka requested changes

2017-08-10 14:44 UTC, katrybacka commented on library/cpp/sandesh_server.cc
>  #include "winutils.h"
Use <winutils.h> instead of "winutils.h"

2017-08-10 14:59 UTC, katrybacka approved these changes

2017-08-10 18:17 UTC, michal-clapinski commented
Retest this please

2017-08-11 05:07 UTC, michal-clapinski commented
Retest this please

2017-08-11 07:08 UTC, merged