JW-168 Implement malloc, free, realloc, zalloc for windows kernel
codilime/contrail-sandesh pull request #5
Opened 2017-02-14 11:43 UTC by mmasztalerczuk

2017-02-14 11:59 UTC, m-kostrzewa approved these changes
couple questions

2017-02-14 11:59 UTC, m-kostrzewa commented on library/c/sandesh.h
> +    }
I think having ```else DbgPrint``` here would be useful for catching errors

2017-02-14 11:59 UTC, m-kostrzewa commented on library/c/sandesh.h
> +    mem = (char*)mem + sizeof(unsigned int);
Why add (and subtract in other functions) sizeof uint?

2017-02-14 12:22 UTC, sodar requested changes

2017-02-14 12:22 UTC, sodar commented on library/c/sandesh.h
> +    void *mem = ExAllocatePoolWithTag(NonPagedPool, size+1, 'RVCO');
`size+1` will not allocate enough space for header and requested buffer size. `size` will be 4 bytes, so you need at least 4 bytes for header.

2017-02-14 12:22 UTC, sodar commented on library/c/sandesh.h
> +    NdisZeroMemory(mem, size);
According to MSDN `RtlZeroMemory` is preferred (see **Requirements** in https://msdn.microsoft.com/en-us/library/windows/hardware/ff564698(v=vs.85).aspx)

2017-02-14 12:22 UTC, sodar commented on library/c/sandesh.h
> +    void *mem = ExAllocatePoolWithTag(NonPagedPool, size+1, 'RVCO');
You can move `'RVCO'` tag into a global variable as in `windows/vrouter_mod.c` in vRouter code.

```
ULONG  SxExtAllocationTag = 'RVCO';
```

2017-02-14 12:22 UTC, sodar commented on library/c/sandesh.h
> +        ExFreePoolWithTag(mem, 'RVCO');
Same as above in `s_malloc`.

2017-02-14 15:36 UTC, mmasztalerczuk commented on library/c/sandesh.h
> +    void *mem = ExAllocatePoolWithTag(NonPagedPool, size+1, 'RVCO');
👍

2017-02-14 15:37 UTC, mmasztalerczuk commented on library/c/sandesh.h
> +    NdisZeroMemory(mem, size);
👍

2017-02-14 15:44 UTC, mmasztalerczuk commented on library/c/sandesh.h
> +        ExFreePoolWithTag(mem, 'RVCO');
:+1:

2017-02-14 16:58 UTC, sodar requested changes

2017-02-14 16:58 UTC, sodar commented on library/c/sandesh.h
> +    s_free(mem);
You have modified `mem` variable before calling `s_free`. It might cause a bug, because `s_free` also modifies it.

2017-02-15 15:17 UTC, m-kostrzewa commented on library/c/sandesh.h
> +    mem = (char*)mem + sizeof(unsigned int);
@mmasztalerczuk explain please

2017-02-15 15:59 UTC, mclapinski requested changes

2017-02-15 15:59 UTC, mclapinski commented on library/c/protocol/thrift_binary_protocol.c
> +#pragma warning(disable: 4701)
maybe include "vr_os.h"?

2017-02-15 15:59 UTC, mclapinski commented on library/c/protocol/thrift_binary_protocol.c
> +unsigned short _fltused = 0;
put this in ifdef _WINDOWS

2017-02-15 15:59 UTC, michal-clapinski commented on library/c/sandesh.h
> +#define os_log(level, format, ...)
So this should happen if not defined _NTKERNEL

2017-02-15 15:59 UTC, michal-clapinski commented on library/c/sandesh.h
> -#define os_log(level, format, ...)       winsyslog(level format, __VA_ARGS__)  //only for now
this should happen if defined _NTKERNEL

2017-02-15 16:30 UTC, sodar approved these changes

2017-02-16 09:35 UTC, merged